tasks:
  - name: Setup Development Env
    init: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      source "/workspace/.cargo/env"
      rustc --version
      rustup update
      rustc --version

vscode:
  extensions:
    - "rust-lang.rust-analyzer"
    - "vadimcn.vscode-lldb"